API:
  API_KEY: API_KEY
  API_SECRET_KEY: API_SECRET_KEY

DATABASE:
  URI: MONGO_URI

BRIDGE: USDT


  
PAIRS: BNBUSDT
  NEOUSDT
  LTCUSDT
  QTUMUSDT
  UNIUSDT
  MATICUSDT
  CHZUSDT
  THETAUSDT
  BTTUSDT
  ONTUSDT
  WINUSDT
  BAKEUSDT

